### ISSUE TITLE
Add Margin to Viewport Width for Project section

### ISSUE THREAD

**Issue by rebeccahongsf** [rebeccahongsf/rebeccahongsf.github.io#5]
![image](https://user-images.githubusercontent.com/34019925/65899791-58a83280-e369-11e9-9133-32e702626d32.png)

**Comment by ibokg** [comment]
Hi! Can I try doing it?

**Comment by rebeccahongsf** [comment]
Hello @ibokg!
Feel free to give it a try. 😄 Thank you!
